{ 
  pkgs 
}:
with pkgs.neovimPlugins; [
  cutlass-nvim
  accelerated-jk-nvim
  luasnip-snippets
  mini-animate
  mini-surround
  mini-hipatterns
  scrollEOF-nvim
  fold-cycle-nvim
  heirline-components-nvim
  telescope-egrepify-nvim
  cmp-luasnip-choice
  yazi-nvim
  tiny-code-action-nvim
  neorg-extras
  neotest-dotnet
  kitty-scrollback-nvim
]
