{
  pkgs
}:
with pkgs.vimPlugins; [
  lazy-nvim
  nvim-hlslens
  nvim-lspconfig
  nvim-notify
  nvim-spider
  nvim-ufo
  nvim-web-devicons
  
  blink-cmp
  blink-compat
  blink-ripgrep-nvim

  cmp-emoji
  cmp-latex-symbols
  # cmp-nvim-lsp-signature-help
  dressing-nvim
  flash-nvim
  friendly-snippets
  gitsigns-nvim
  heirline-nvim
  highlight-undo-nvim
  hydra-nvim
  indent-blankline-nvim
  luasnip
  marks-nvim
  neoconf-nvim
  neodev-nvim
  neorg
  neorg-telescope
  noice-nvim
  nui-nvim
  catppuccin-nvim
  plenary-nvim
  promise-async
  rainbow-delimiters-nvim
  telescope-nvim
  telescope-fzf-native-nvim
  todo-comments-nvim
  ultimate-autopair-nvim
  vim-illuminate
  rustaceanvim
  smart-splits-nvim
  twilight-nvim
  undotree
  vimtex
  yanky-nvim
  cmp_yanky
  vim-pencil
  zen-mode-nvim
  inc-rename-nvim
  bufdelete-nvim
  glance-nvim
  neo-tree-nvim
  which-key-nvim
  true-zen-nvim
  treesj
  zk-nvim
  image-nvim
  nabla-nvim
  no-neck-pain-nvim
  nvim-dap
  nvim-dap-ui
  nvim-dap-virtual-text
  # neotest-dotnet
  neotest
  neotest-golang
  neotest-gradle
  neotest-java
  neotest-python
  nvim-coverage
  lsp_lines-nvim
]
